@baseUrl = http://localhost:3000
@jwt = ''

# signup
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "guijiangheng",
  "email": "guijiangheng@gmail.com",
  "password": "123456"
}

###

# @name login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "guijiangheng@gmail.com",
  "password": "123456"
}

###

@token = {{login.response.body.$.user.token}}

# @name createArticle
POST {{baseUrl}}/articles
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "article": {
    "title": "sdf",
    "description": "sdf",
    "body": "sdf",
    "tagList": ["sdf"]
  }
}

###

@slug = {{createArticle.response.body.$.article.slug}}

# Get an article by slug
GET {{baseUrl}}/articles/{{slug}}

###

# Delete an article by slug
DELETE {{baseUrl}}/articles/{{slug}}
Authorization: Bearer {{token}}

###

# Favorite an article
POST {{baseUrl}}/articles/{{slug}}/favorite
Authorization: Bearer {{token}}

###

# UnFavorite an article
DELETE {{baseUrl}}/articles/{{slug}}/favorite
Authorization: Bearer {{token}}

###

# Delete an article
DELETE {{baseUrl}}/articles/{{slug}}
Authorization: Bearer {{token}}

###

# @name createComment
# Create a comment
POST {{baseUrl}}/articles/{{slug}}/comments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "comment": {
    "body": "this is a comment"
  }
}

###
@id = {{createComment.response.body.$.comment.id}}

# Get article comments
GET {{baseUrl}}/articles/{{slug}}/comments

###

# Delete an comment
DELETE {{baseUrl}}/articles/{{slug}}/comments/{{id}}
Authorization: Bearer {{token}}

